
package client.ws.rytsa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "TestService", targetNamespace = "http://valuaciones.itau.rytsa/", wsdlLocation = "ItauMTM.wsdl")
public class TestService
    extends Service
{

    public  static URL TESTSERVICE_WSDL_LOCATION = null;

    public TestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService() {
        super(TESTSERVICE_WSDL_LOCATION, new QName("http://valuaciones.itau.rytsa/", "TestService"));
    }

    /**
     * 
     * @return
     *     returns Test
     */
    @WebEndpoint(name = "TestPort")
    public Test getTestPort() {
        return (Test)super.getPort(new QName("http://valuaciones.itau.rytsa/", "TestPort"), Test.class);
    }

}
