
package client.ws.rytsa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Test", targetNamespace = "http://valuaciones.itau.rytsa/")
public interface Test {


    /**
     * 
     * @param arg0
     * @return
     *     returns client.ws.rytsa.InformarNovedadesValuacionesXmlRequest
     * @throws ParseException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularMTMNdf", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.CalcularMTMNdf")
    @ResponseWrapper(localName = "calcularMTMNdfResponse", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.CalcularMTMNdfResponse")
    public InformarNovedadesValuacionesXmlRequest calcularMTMNdf(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns client.ws.rytsa.InformarNovedadesValuacionesXmlRequest
     * @throws ParseException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularMTMSwap", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.CalcularMTMSwap")
    @ResponseWrapper(localName = "calcularMTMSwapResponse", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.CalcularMTMSwapResponse")
    public InformarNovedadesValuacionesXmlRequest calcularMTMSwap(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetBBDD", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.ResetBBDD")
    @ResponseWrapper(localName = "resetBBDDResponse", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.ResetBBDDResponse")
    public String resetBBDD(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ParseException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testSuma1Dia", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.TestSuma1Dia")
    @ResponseWrapper(localName = "testSuma1DiaResponse", targetNamespace = "http://valuaciones.itau.rytsa/", className = "client.ws.rytsa.TestSuma1DiaResponse")
    public String testSuma1Dia(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception, ParseException_Exception
    ;

}
